# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets

from View.EditCards import EditCards
from View.EditDecks import EditDecks

class AdminLandingPage(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 20, 331, 261))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.edit_cards_button = QtWidgets.QPushButton(self.widget)
        self.edit_cards_button.setMaximumSize(QtCore.QSize(80, 25))
        self.edit_cards_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.edit_cards_button.setObjectName("edit_cards_button")
        self.edit_cards_button.clicked.connect(self.goToEditCards)
        self.gridLayout.addWidget(self.edit_cards_button, 1, 1, 1, 1)
        self.edit_decks_button = QtWidgets.QPushButton(self.widget)
        self.edit_decks_button.setMaximumSize(QtCore.QSize(80, 25))
        self.edit_decks_button.setObjectName("edit_decks_button")
        self.edit_decks_button.clicked.connect(self.goToEditDecks)
        self.gridLayout.addWidget(self.edit_decks_button, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        self.admin_mode_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.admin_mode_label.setFont(font)
        self.admin_mode_label.setAlignment(QtCore.Qt.AlignCenter)
        self.admin_mode_label.setObjectName("admin_mode_label")
        self.gridLayout.addWidget(self.admin_mode_label, 0, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.edit_cards_button.setText(_translate("Dialog", "Edit Cards"))
        self.edit_decks_button.setText(_translate("Dialog", "Edit Decks"))
        self.admin_mode_label.setText(_translate("Dialog", "Admin Mode"))

    def goToEditCards(self):
        self.editCards = QtWidgets.QWidget()
        self.ui = EditCards()
        self.ui.setupUi(self.editCards)
        self.editCards.show()

    def goToEditDecks(self):
        self.editDecks = QtWidgets.QWidget()
        self.ui = EditDecks()
        self.ui.setupUi(self.editDecks)
        self.editDecks.show()